
import { arrowBackSharp, bodySharp, chevronUpSharp, colorPalette, ellipsisVerticalSharp, globe, homeSharp, logInSharp, logOutSharp, menu, pencilSharp, personAddSharp, personCircleSharp, personRemoveSharp, personSharp, reloadSharp, remove, reorderThree, shareSocialSharp, statsChartSharp, trophySharp, document, add, checkmarkSharp, clipboardSharp, ellipsisVerticalCircleSharp, closeCircleSharp, addCircleSharp, closeSharp, trashBinSharp, copySharp } from 'ionicons/icons';

export const appIcons = {
  reorderThree,
  remove,
  menu,
  personSharp,
  personAddSharp,
  personRemoveSharp,
  personCircleSharp,
  logInSharp,
  logOutSharp,
  reloadSharp,
  homeSharp,
  statsChartSharp,
  bodySharp,
  trophySharp,
  arrowBackSharp,
  ellipsisVerticalSharp,
  shareSocialSharp,
  pencilSharp,
  chevronUpSharp,
  colorPalette, 
  document, 
  globe,
  add, 
  checkmarkSharp, 
  clipboardSharp,
  ellipsisVerticalCircleSharp,
  addCircleSharp,
  closeSharp,
  trashBinSharp,
  copySharp
};
